### ISSUE TITLE
"Save as image" action for a graph failes to create image

### ISSUE THREAD

**Issue by rcoscali** [CoatiSoftware/SourcetrailBugTracker#511] opened 2017-11-08 17:48 UTC
Any call to save as image runs correctly the first time, but fails afterwards.
It either generate a weird image or no image at all

**Comment by egraether** [comment] 2017-11-08 18:11
Thanks for reporting. Can't reproduce on macOS. Which operating system are you using?

**Comment by rcoscali** [comment] 2017-11-10 17:20
windows

Le 8 nov. 2017 19:11, Eberhard Gräther <notifications@github.com> a écrit :

Thanks for reporting. Can't reproduce on macOS. Which operating system are you using?

**Comment by rcoscali** [comment] 2017-11-10 17:21
didn't tried on linux. I will...


Le 10 nov. 2017 18:20, Cohen-Scali Rémi <remi.cohen-scali@nagra.com> a écrit :
windows

Le 8 nov. 2017 19:11, Eberhard Gräther <notifications@github.com> a écrit :

Thanks for reporting. Can't reproduce on macOS. Which operating system are you using?

**Comment by rcoscali** [comment] 2017-11-14 14:47
Here is an example with last version
![cdialogplus](https://user-images.githubusercontent.com/4035461/32785958-0c8b5a80-c953-11e7-817a-1f1663b4978e.png)

**Comment by rcoscali** [comment] 2017-11-14 14:54
and another one 536x27262.
![cdialogplus-inheritance2](https://user-images.githubusercontent.com/4035461/32786359-ffaea186-c953-11e7-950a-cfaf08b82410.png)

**Comment by rcoscali** [comment] 2017-11-15 02:06
Hi

Actually linux is behaving exactly the same as windows. Image is 1369x12758


Best

Rémi
________________________________
De : Cohen-Scali Rémi <remi.cohen-scali@nagra.com>
Envoyé : vendredi 10 novembre 2017 18:21:02
À : CoatiSoftware/SourcetrailBugTracker
Objet : Re: [CoatiSoftware/SourcetrailBugTracker] "Save as image" action for a graph failes to create image (#511)

didn't tried on linux. I will...


Le 10 nov. 2017 18:20, Cohen-Scali Rémi <remi.cohen-scali@nagra.com> a écrit :
windows

Le 8 nov. 2017 19:11, Eberhard Gräther <notifications@github.com> a écrit :

Thanks for reporting. Can't reproduce on macOS. Which operating system are you using?

-

**Comment by egraether** [comment] 2017-11-15 07:00
Alright, thanks will look into it.

**Comment by mlangkabel** [comment] 2017-11-17 11:25
It looks like the old elements in the graph do not get deleted right away. So if you open up a very large graph (clicking on the `Classes` node in the overview) and switch to the symbol you want to save as image directly, the image will become very large. If you activate some other symbols with small graphs inbetween, the saved image may not be matching your graph's size exactly but it will be not rediculously large.

**Comment by egraether** [comment] 2017-11-17 21:51
Turned out the problem was that the size of the scene did only grow, so the image is always the size of the largest graph shown in the session.

Fixed with 2017.4.54

**Closed by egraether** 2017-11-17 21:51 UTC
Labels: bug, Linux, Windows

**Comment by rcoscali** [comment] 2017-11-17 21:57
Thanks for the workaround. Will it be fixed in some way some day ? If yes will you have a bug id ? thx

Provenance : Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows 10

De : Malte Langkabel<mailto:notifications@github.com>
Envoyé le :vendredi 17 novembre 2017 12:41
À : CoatiSoftware/SourcetrailBugTracker<mailto:SourcetrailBugTracker@noreply.github.com>
Cc : Cohen-Scali Rémi<mailto:remi.cohen-scali@nagra.com>; Author<mailto:author@noreply.github.com>
Objet :Re: [CoatiSoftware/SourcetrailBugTracker] "Save as image" action for a graph failes to create image (#511)


It looks like the old elements in the graph do not get deleted right away. So if you open up a very large graph (clicking on the Classes node in the overview) and switch to the symbol you want to save as image directly, the image will become very large. If you activate some other symbols with small graphs inbetween, the saved image may not be matching your graph's size exactly but it will be not rediculously large.

-

**Comment by rcoscali** [comment] 2017-11-17 22:07
thx

Provenance : Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows 10

De : Eberhard Gräther<mailto:notifications@github.com>
Envoyé le :vendredi 17 novembre 2017 23:06
À : CoatiSoftware/SourcetrailBugTracker<mailto:SourcetrailBugTracker@noreply.github.com>
Cc : Cohen-Scali Rémi<mailto:remi.cohen-scali@nagra.com>; Author<mailto:author@noreply.github.com>
Objet :Re: [CoatiSoftware/SourcetrailBugTracker] "Save as image" action for a graph failes to create image (#511)


Closed #511<https://github.com/CoatiSoftware/SourcetrailBugTracker/issues/511>.

-

**Comment by rcoscali** [comment] 2017-11-17 22:22
Nice thx

Provenance : Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows 10

De : Eberhard Gräther<mailto:notifications@github.com>
Envoyé le :vendredi 17 novembre 2017 23:21
À : CoatiSoftware/SourcetrailBugTracker<mailto:SourcetrailBugTracker@noreply.github.com>
Cc : Cohen-Scali Rémi<mailto:remi.cohen-scali@nagra.com>; Author<mailto:author@noreply.github.com>
Objet :Re: [CoatiSoftware/SourcetrailBugTracker] "Save as image" action for a graph failes to create image (#511)


Turned out the problem was that the size of the scene did only grow, so the image is always the size of the largest graph shown in the session.

Fixed with 2017.4.54

-
