### ISSUE TITLE
No files indexed in a CDB project

### ISSUE THREAD

**Issue by TTimo** [CoatiSoftware/SourcetrailBugTracker#388] opened 2017-05-22 15:26 UTC
Sourcetrail 0.12 linux x86_64

I generated a fresh compile_commands.json using the latest Bear https://github.com/rizsotto/Bear
There are 780 files, but when I run indexing (full refresh etc.), no files are indexed at all:

https://gyazo.com/1ec95dbb1c5b297245185d75c02879c8
https://gyazo.com/d9159929b32b0ce895cdfa21977d13dc

I can provide the CDB etc.

**Comment by egraether** [comment] 2017-05-22 15:31
Yes please provide the CDB. You can also send it to mail@sourcetrail.com if you prefer.

**Comment by egraether** [comment] 2017-05-22 20:54
I just had a look at your files and it looks to me as if the `.cpp` files listed within the `compile_commands.json` file simply don't exist.

The `compile_commands.json` file does not reference any files within the `Source` directory, just files within the `Intermediate` directory or files named `.generated.cpp`. I guess there might be a preprocessing step that creates these files first. Did run a build yet?

To confirm this can you please check if e.g. this file exists:
`../Valve/UnrealEngine/Engine/Source/../Intermediate/Build/Linux/B4D820EA/UE4Editor/Debug/AnimationEditor/Module.AnimationEditor.cpp`

**Comment by TTimo** [comment] 2017-05-23 02:18
compile_commands.json was captured by using bear to capture an entire
build. More specifically, compile_commands.json was produced by running
'bear make UE4Editor-Linux-Debug' on a clean tree.

The Module.*.cpp files were created as part of UE4's custom build process,
and actually compiled (since bear is a pass-through).
I did verify that the files still existed on disk and were not deleted
after the build. The ones I checked definitely existed.

The assembly of several .cpp files into a single one is a process called
'unity' in UE4 which is supposed to make the overall compilation faster. I
will look for a way to disable unity entirely and see if I get better
results on the indexing.

TTimo

**Comment by egraether** [comment] 2017-05-23 08:49
No, if the files do exist then the problem is within Sourcetrail. We just had a look and could reproduce the issue with a compile_commands.json with non-canonical file paths.

**Comment by egraether** [comment] 2017-05-23 09:58
Fixed with 0.12.50

This issue was caused in a recent rewrite to extend for multi-language projects, where we broke support for relative paths with the `compile_commands.json` file. Cmake uses absolute paths when creating the `compile_commands.json`, so this issue never appeared in our tests.

As workaround you currently need to make all relative file paths absolute within the `compile_commands.json`. Simply replace all occurrences of `"file": "..` with `"file": "<your_user_dir>/Valve/UnrealEngine/Engine`.

Thank you for reporting this issue! I'm closing it now, but you can still comment or reopen.

**Closed by egraether** 2017-05-23 09:58 UTC
Labels: bug
