### ISSUE TITLE
Source code window has no horizontal scrollbar

### ISSUE THREAD

**Issue by TTimo** [CoatiSoftware/SourcetrailBugTracker#498] opened 2017-10-26 16:31 UTC
linux x86_64

The source code window lacks a horizontal scrollbar. I have to widen the window sometimes with long lines of code..

**Comment by mlangkabel** [comment] 2017-10-26 18:55
This is an issue on all platforms. The horizontal scrollbar as well as the file's title are part of the code snippet and may vertically be scrolled out of sight.

**Comment by egraether** [comment] 2017-11-29 19:38
This is a duplicate of #432 
We get this feedback a lot lately, so it has become a priority for the next release to fix this.

**Closed by egraether** 2017-11-29 19:38 UTC
Labels: duplicate
