### ISSUE TITLE
Problem with parsing an Android project

### ISSUE THREAD

**Issue by VDenis** [CoatiSoftware/SourcetrailBugTracker#377] opened 2017-05-13 09:41 UTC
Hi!

I have a problem with parsing an Android project.
I added a [screenshot](https://cloud.githubusercontent.com/assets/5451716/26024408/44d0fb72-37d9-11e7-8e20-62271abf1578.png).

Links:
1) [TranslateFragment.java](https://github.com/VDenis/YandexTranslator/blob/master/app/src/main/java/com/app/vdlasov/yandextranslate/ui/fragment/TranslateFragment.java)
2) [YandexTranslator](https://github.com/VDenis/YandexTranslator)

Regards, Denis

**Comment by VDenis** [comment] 2017-05-15 19:23
@mlangkabel Yes, you are correct.

**Comment by mlangkabel** [comment] 2017-05-16 07:04
Ok, so my first assumption is that the issue is caused by the project setup. What kind of project did you create? Did you add the `.java` file (or the folder that contains the file) where `android.widget.ImageButton` is defined to your indexed source files?

**Comment by VDenis** [comment] 2017-05-21 19:24
Project type - java. I added `android.widget.ImageButton` to the project indexed paths.
It still doesn't work.

**Comment by mlangkabel** [comment] 2017-05-24 06:48
I'm trying to reproduce the issue. Can you give me a hint on where to download the source code for all the android classes?

**Comment by VDenis** [comment] 2017-05-28 20:07
@mlangkabel 
You can dowmload it from the following github project:
https://github.com/android/platform_frameworks_base
E.g. Image button https://github.com/android/platform_frameworks_base/blob/master/core/java/android/widget/ImageButton.java

I added next folders view and widget.

**Comment by mlangkabel** [comment] 2017-05-30 14:55
To reproduce your issue I have downloaded the code you specified and set up the project as shown by the screenshot below. I'm using the latest release of Sourcetrail (0.12.25) and everything seems to be working correctly. As you can see in the background of the screenshot the class `ImageButton` is indexed and the references are found.

@VDenis: Is this the result you would have expected? Can you tell if your project setup is any different from mine?

![imagebutton](https://cloud.githubusercontent.com/assets/16242920/26589302/f6b3fade-4557-11e7-84c5-5ca4a75d98fc.png)

**Comment by VDenis** [comment] 2017-05-31 20:28
@mlangkabel Not exactly. I don't have a problem with a class information, i can't find all reference of local variable.
For example: `private ImageButton btnLangSwitch;`

**Comment by mlangkabel** [comment] 2017-06-02 14:59
That's odd. When using the project setup I posted above I'm able to find that reference. But in general we are still having some cases where references are not resolved. In those cases we record a reference to `unsolved-symbol`. The release that we have scheduled for next week will solve many but not all of those cases.

**Comment by egraether** [comment] 2017-06-23 13:58
@VDenis Can you please try if the problem still persists in our latest build? https://www.sourcetrail.com/downloads

**Comment by egraether** [comment] 2019-08-02 23:35
No update in 2 years. I think we changed Java indexers meanwhile, so this is likely not valid anymore. Closing.

**Closed by egraether** 2019-08-02 23:35 UTC
Labels: await reply
