### ISSUE TITLE
Add "Show in IDE" to Node context menu

### ISSUE THREAD

**Issue by studgeek** [CoatiSoftware/SourcetrailBugTracker#687] opened 2019-04-20 01:25 UTC
It would be very handy if "Show in IDE" was also available in each Node's context menu. That would allow the Sourcetrail Code Window to be closed. Then user could use Sourcetrail Graph Window along side the IDE with its source code views.

On a related note, it would be great if there was a "Autoshow in IDE" option. When enabled it would Send to IDE each time the Node active changed. So the two would stay in sync when moving around in Sourcetrail.

**Comment by egraether** [comment] 2019-04-23 11:20
Implemented with 2019.1.34
Added `Show Definition in IDE` action to context menu for nodes (shortcut `Ctrl + Left Click`).

Your second suggestion is a duplicate of #360

**Closed by egraether** 2019-04-23 11:20 UTC
Labels: feature
