### ISSUE TITLE
Visual Studio plugin not working on VS 2013

### ISSUE THREAD

**Issue by egraether** [CoatiSoftware/SourcetrailBugTracker#367] opened 2017-04-18 12:25 UTC
reported with Coati 0.11.15

﻿﻿Create CDB action doesn't show a dialog:
![image003](https://cloud.githubusercontent.com/assets/201867/25130520/bec0ad42-2442-11e7-975d-e84219488c83.png)

No options shown for the Coati plugin:
![image002](https://cloud.githubusercontent.com/assets/201867/25130544/d3a5661c-2442-11e7-8c72-b5bc6b6a9c76.jpg)

**Comment by mlangkabel** [comment] 2017-05-22 07:54
It looks like this issue is caused by the Sourcetail Plugin using some dependencies that are not available in VS2013.

**Comment by mlangkabel** [comment] 2017-06-02 14:29
I was able to reproduce this issue once but on that occasion Visual Studio warned be beforehand that something has gone wrong and things could be fishy. Did that occurr in this case?

**Comment by mlangkabel** [comment] 2017-07-10 09:19
Version 1.0 of the Visual Studio extension is now available in the VS gallery. To update just click `Tools` -> `Extensions and Updates...`. Under the `Updates` section choose to update the `Sourcetrail Extension` entry.

Please check if the issue still exists.

**Comment by mlangkabel** [comment] 2017-08-07 13:49
Closing this issue now because it's probably already resolved and we haven't received any further feedback. Please post new issues regarding the Visual Studio extension to the [Sourcetrail Extension issue tracker](https://github.com/CoatiSoftware/vs-sourcetrail/issues).

**Closed by mlangkabel** 2017-08-07 13:49 UTC
Labels: await reply, bug, Windows
