### ISSUE TITLE
Probably problem handling NTFS Junction points

### ISSUE THREAD

**Issue by davidhunter22** [CoatiSoftware/SourcetrailBugTracker#102] opened 2016-06-23 17:58 UTC
I use Cmake 3.5.2 to generate a Visual Studio 2015 solution containing about 100 projects. Coati seems to be able to read the solution and projects and  eventually comes up with the "New project from VS Solution" window which annoyingly is not resizable. Anyway there is a plausible looking list of files in the "Project Paths"  and paths in the "Include Paths". However if I click "Show Files" it says "0 files will be indexed". When I hit create I get a popup saying "These paths do no exist:" with a massive list of paths. I can't actually see the full paths or how many there are as this window is also non resizable and has no scroll bar. So my suspicion is that the problem is that CMake VS builds are normally out of tree in that the VS solution and projects do not live in the same directories as the source files. CMake generated project files are also quite different to those that VS generates itself, although they are still valid MSBuild and do work when loaded by VS.

![capture](https://cloud.githubusercontent.com/assets/8083830/16314095/8600cefa-3939-11e6-8575-930b5f121b94.PNG)

**Comment by egraether** [comment] 2016-06-23 18:13
We will rework the windows of the project setup UI for the next release. You are right, they should be resizable.

I doubt that the issue is caused by the VS solution being in a different directory. The paths in the "These source files do not exist"-Popup are absolute. But on your screenshot it looks like you have Unicode characters within your paths that are not correctly displayed. I suspect that's what causes the problem.

**Comment by davidhunter22** [comment] 2016-06-23 20:58
I don't think I have any special characters in my paths. CMake when it generates a vcxproj file puts the absolute path of each .h and .cpp file so I have lines like the following 

   <ClInclude Include="C:\Users\david\devel\ReflexLibs\trunk\trunk\reflex_utils\Addin.h" />

The non displayable characters in your dialogs seems to correspond to the "C:\". I did notice in your dialog you are displaying a "/" character as the separator not a "\" so I assume you are doing some processing on the paths you find in the vxcproj file. I would attach one of the vcxproj files but github doesn't seem to like that type of file.

Anything else I can send you might find useful?

**Comment by davidhunter22** [comment] 2016-06-23 21:02
Oh if your going to rework the popup windows can you make sure at least error message ones can be cut and paste. This helps sending the test of errors to people

**Comment by egraether** [comment] 2016-06-30 11:59
Made windows resizeable and fixed popup for non-existing paths to show them in a text field for details with 0.7.0.17

**Comment by egraether** [comment] 2017-08-29 15:44
@davidhunter22 Can you please test this again with our new [Visual Studio Plugin](https://marketplace.visualstudio.com/items?itemName=vs-publisher-1208751.SourcetrailExtension) and the [latest build](https://www.sourcetrail.com/downloads)?

**Comment by egraether** [comment] 2017-11-17 23:51
No updates in months. VS solution parser has been discontinued. Issue did not occur to other users. Probably fixed. Closing.

**Closed by egraether** 2017-11-17 23:51 UTC
Labels: await reply, bug
