### ISSUE TITLE
after Refresh, History menu items do not work

### ISSUE THREAD

**Issue by pwillard2** [CoatiSoftware/SourcetrailBugTracker#572] opened 2018-04-30 20:27 UTC
I just did a full Refresh of the project (Edit-> Refresh-> All files).
After refresh completed, when I go back to my History items (History --> some previous item), the windows do not show the expected information (jump to some other place!).
(I am using 2018.2.23 - 64 bit on Centos)

**Comment by egraether** [comment] 2018-04-30 20:29
What do you mean by jump to some other place?
Does the graph view show the correct information?
Does the code view show the correct file, but at a different scroll position?

**Comment by pwillard2** [comment] 2018-04-30 21:40
graph and code view are 'in-sync', but they do NOT represent the expected information  (wrong file!).
Basically graph and code show something completely unrelated to what is in the history (or in any history item!).
Weird.

**Comment by egraether** [comment] 2018-04-30 22:04
Thanks for the infos, I will investigate this and try to reproduce.

**Comment by mlangkabel** [comment] 2018-06-26 12:14
Didn't manage to reproduce this issue on Windows.

**Comment by pwillard2** [comment] 2018-06-26 16:31
I just tried again (on version 2018.2.77) and it still does not work.
In History I just selected a file (SeachController.cpp) and the following happens:
- the Search window shows the right filename,
- but the Code and Graph windows show a TextButton class !!!!!!!!!!!!!
Looking at the log it says:
09:23:19 | 140583644079872 | INFO: send MessageWindowFocus 
09:25:24 | 140583644079872 | INFO: send MessageWindowFocus 
09:25:24 | 140583644079872 | INFO: send MessagePingReceived 
09:25:36 | 140583644079872 | INFO: send MessageSearch @
09:25:36 | 140583652472576 | INFO: send MessageActivateTokens 893183 
09:25:36 | 140583644079872 | INFO: send MessageStatus Activate "Roku::TextButton": 1 result with 1 reference in 1 file
09:25:36 | 140583644079872 | StatusBarController.cpp:79 setStatus() | INFO: STATUS Activate "Roku::TextButton": 1 result with 1 reference in 1 file
09:25:40 | 140583644079872 | INFO: send MessageWindowFocus 

Could Tokens 893183 have changed after a Full re-indexing ??

**Comment by egraether** [comment] 2018-06-26 16:35
Yes, they the token ids can change and in this case the token should be searched by name. I don't know why this fallback is not working. I will look into it when I find time.

**Comment by pwillard2** [comment] 2018-06-26 16:40
Maybe it's because my project has some FATAL errors.  Try that just in case....

**Comment by egraether** [comment] 2018-06-26 19:03
No, that doesn't matter here

**Comment by egraether** [comment] 2018-06-26 22:05
I managed to reproduce it. As stated the bug is in the history menu, not in the history dropdown list.

Fixing it is not so simple. It is caused by a design issue. I will need to do some refactoring.

**Comment by pwillard2** [comment] 2018-06-26 22:54
Thanks for letting me know. 
Note that I would rather have you guys fix issue #577 first. Sometimes I really need to have one file parsed completely, and it would be really helpful to know the issues for that single file.

**Comment by egraether** [comment] 2018-06-30 00:21
Fixed with 2018.2.85

**Closed by egraether** 2018-06-30 00:21 UTC
Labels: bug
