### ISSUE TITLE
Crashes when opening preferences

### ISSUE THREAD

**Issue by neurospochtsfroind** [CoatiSoftware/SourcetrailBugTracker#545] opened 2018-01-30 07:19 UTC
Crashes immediatly when opening preferences. Makes no difference when using cmd-, or using the menu. Tested on macOs 10.12.6.

First part of error dump:

    Process:               Sourcetrail [47989]
    Path:                  /Applications/Sourcetrail.app/Contents/MacOS/Sourcetrail
    Identifier:            com.sourcetrail
    Version:               ??? (2018.1-17-g556ed98d)
    Code Type:             X86-64 (Native)
    Parent Process:        ??? [1]
    Responsible:           Sourcetrail [47989]
    User ID:               501

    Date/Time:             2018-01-30 08:21:38.914 +0100
    OS Version:            Mac OS X 10.12.6 (16G1212)
    Report Version:        12
    Anonymous UUID:        0E0E149F-DEE7-5E2E-BD7F-73D68BEA9DC2

    Sleep/Wake UUID:       25E429CF-8749-4341-B451-30FEDA8ECDB7

    Time Awake Since Boot: 97000 seconds
    Time Since Wake:       5000 seconds

    System Integrity Protection: enabled

    Crashed Thread:        0  Dispatch queue: com.apple.main-thread

    Exception Type:        EXC_CRASH (SIGABRT)
    Exception Codes:       0x0000000000000000, 0x0000000000000000
    Exception Note:        EXC_CORPSE_NOTIFY

    Application Specific Information:
    abort() called

    Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
    0   libsystem_kernel.dylib          0x00007fffc5e2cd42 __pthread_kill + 10
    1   libsystem_pthread.dylib         0x00007fffc5f1a457 pthread_kill + 90
    2   libsystem_c.dylib               0x00007fffc5d92420 abort + 129
    3   org.qt-project.QtCore           0x0000000103a01259 0x1039ea000 + 94809
    4   org.qt-project.QtCore           0x0000000103a02c27 QMessageLogger::fatal(char const*, ...) const + 231
    5   org.qt-project.QtCore           0x00000001039fd78c qt_assert(char const*, char const*, int) + 76
    6   com.sourcetrail                 0x000000010058d324 QtDirectoryListBox::addListBoxItem() + 372
    7   com.sourcetrail                 0x000000010058bd33 QtDirectoryListBox::addListBoxItemWithText(QString const&) + 19
    8   com.sourcetrail                 0x000000010058e549 QtDirectoryListBox::setStringList(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, bool) + 441
    9   com.sourcetrail                 0x000000010058e2c3 QtDirectoryListBox::setList(std::__1::vector<FilePath, std::__1::allocator<FilePath> > const&, bool) + 195
    10  com.sourcetrail                 0x000000010064c7b6 QtProjectWizzardContentPathsHeaderSearchGlobal::load() + 54
    11  com.sourcetrail                 0x00000001006400a1 QtProjectWizzardContentGroup::load() + 49
    12  com.sourcetrail                 0x0000000100627915 QtPreferencesWindow::windowReady() + 197
    13  com.sourcetrail                 0x000000010062dd56 QtWindow::setup() + 1030
    14  org.qt-project.QtCore           0x0000000103c0e9cb QMetaObject::activate(QObject*, int, int, void**) + 731
    15  org.qt-project.QtWidgets        0x0000000102da8bdf QAction::activate(QAction::ActionEvent) + 303
    16  org.qt-project.QtCore           0x0000000103c0ea81 QMetaObject::activate(QObject*, int, int, void**) + 913
    17  org.qt-project.QtCore           0x0000000103c07b0c QObject::event(QEvent*) + 156
    18  org.qt-project.QtWidgets        0x0000000102db1bdd QApplicationPrivate::notify_helper(QObject*, QEvent*) + 269
    19  org.qt-project.QtWidgets        0x0000000102db44ac QApplication::notify(QObject*, QEvent*) + 5852
    20  org.qt-project.QtCore           0x0000000103bdd9f4 QCoreApplication::notifyInternal2(QObject*, QEvent*) + 164
    21  org.qt-project.QtCore           0x0000000103bde740 QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) + 560
    22  libqcocoa.dylib                 0x000000010596325e 0x10593a000 + 168542
    23  libqcocoa.dylib                 0x0000000105963b21 0x10593a000 + 170785
    24  com.apple.CoreFoundation        0x00007fffaffd43e1 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
    25  com.apple.CoreFoundation        0x00007fffaffb565c __CFRunLoopDoSources0 + 556
    26  com.apple.CoreFoundation        0x00007fffaffb4b46 __CFRunLoopRun + 934
    27  com.apple.CoreFoundation        0x00007fffaffb4544 CFRunLoopRunSpecific + 420
    28  com.apple.HIToolbox             0x00007fffaf513ebc RunCurrentEventLoopInMode + 240
    29  com.apple.HIToolbox             0x00007fffaf513bf9 ReceiveNextEventCommon + 184
    30  com.apple.HIToolbox             0x00007fffaf513b26 _BlockUntilNextEventMatchingListInModeWithFilter + 71
    31  com.apple.AppKit                0x00007fffadaaaa54 _DPSNextEvent + 1120
    32  com.apple.AppKit                0x00007fffae2267ee -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 2796
    33  com.apple.AppKit                0x00007fffada9f3db -[NSApplication run] + 926
    34  libqcocoa.dylib                 0x00000001059629bf 0x10593a000 + 166335
    35  org.qt-project.QtCore           0x0000000103bd9631 QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) + 401
    36  org.qt-project.QtCore           0x0000000103bde099 QCoreApplication::exec() + 393
    37  com.sourcetrail                 0x000000010054e71d main + 2685
    38  libdyld.dylib                   0x00007fffc5cfe235 start + 1

**Comment by egraether** [comment] 2018-01-30 07:30
Thanks for reporting! It's the same problem as #544. I will look into it today and upload a new build when it's fixed.

**Comment by mlangkabel** [comment] 2018-01-30 08:14
FYI: cannot reproduce this on windows

**Comment by egraether** [comment] 2018-01-30 10:08
Fixed with 2018.1.19 ([download here](https://www.sourcetrail.com/downloads))

The crash was caused by an assert in QListWidget when getting a list iterator on an empty list. The underlying issue was present on all platforms since 2018.1.8. It should have been noticed right away, but for some reason it only appeared in the released macOS build.

Thanks for reporting again!

**Closed by egraether** 2018-01-30 10:08 UTC
Labels: bug
