### ISSUE TITLE
Crash when opening compile_commands.json

### ISSUE THREAD

**Issue by bzcheeseman** [CoatiSoftware/SourcetrailBugTracker#544] opened 2018-01-29 21:56 UTC
Sourcetrail version: 2018.1.18, 64bit
Platform: macOS 10.12.6

I'm trying to create a new project and sourcetrail crashes whenever I try to create a new source group from a compile_commands.json file.

To reproduce: Open Sourcetrail and create a new project from scratch. Add a source group from compilation database and select your .json file.

**Comment by egraether** [comment] 2018-01-29 22:00
Yes, I can reproduce that. Thanks for reporting!

**Comment by egraether** [comment] 2018-01-30 10:08
Fixed with 2018.1.19 ([download here](https://www.sourcetrail.com/downloads))

The crash was caused by an assert in QListWidget when getting a list iterator on an empty list. The underlying issue was present on all platforms since 2018.1.8. It should have been noticed right away, but for some reason it only appeared in the released macOS build.

Thanks for reporting again!

**Closed by egraether** 2018-01-30 10:08 UTC
Labels: bug
